# validate artifact definitions
# build+test+publish arifacts (docker images, VM images)
#   tests:
#     docker master:
#       is exposing port 8080?
#       jenkins service is running?
#       health changes from 'starting' to 'healthy' within 30s/1m
#     docker nginx:
#       is exposing port 80?
#       epTODO add a health check for this
#       some other stuff
# manual deploy step?

stages:
  - validate

validate:packer-templates:
  stage: validate
  image:
    name: hashicorp/packer:1.2.4
    entrypoint: ["/bin/sh", "-c"]
  script:
    - cd infrastructure/images
    - for t in $(ls | grep .json$); do echo "Validating ${t}" && packer validate ${t}; done

validate:inspec-tests:
  stage: validate
  image:
    name: chef/inspec:2.2.27
    entrypoint: ["/bin/sh", "-c"]
  script:
    - cd infrastructure/inspec-profiles
    - inspec check aws-baseline
    - inspec check debian-baseline
    - inspec check jenkins-master
