options:
  max-time: 2

pipelines:
  branches:
   '**':
      - parallel:
        - step:
            image: hashicorp/packer:1.2.3
            name: Validate Packer Templates
            script:
              - cd infrastructure
              - packer validate jenkins_master_ami.json
