options:
  max-time: 3

pipelines:
  branches:
    master:
      - step:
          name: Build and publish jenkins master docker images
          image: docker/compose:1.21.2
          script:
            - sh ensure-pipeline-env-vars-set.sh
            - cd docker
            - echo "JENKINS_ROOT=${JENKINS_ROOT}" > network.env
            - docker-compose build
            - docker login --username=chuck202 --password=${DOCKER_HUB_PASSWORD}
            - docker push chuck202/master:0.1
            - docker push chuck202/nginx:0.1
            - docker push chuck202/data:0.1
          services:
            - docker
          max-time: 5
      - step:
        name: Deploy to AWS
        deployment: test
        script:
          - cd infrastructure
          - terraform init # epTODO ensure that the AWS env vars are set
          - echo yes | terraform apply # epTODO another script line for config mgmt
    '**':
      - parallel:
        - step:
            image: hashicorp/packer:1.2.3
            name: Validate Packer templates
            script:
              - cd infrastructure/images
              - packer validate jenkins_master_ami.json
        - step:
            image: hashicorp/terraform:0.11.7
            name: Validate Terraform IaC
            script:
              - cd infrastructure
              - terraform init
              - terraform validate .
        - step:
            image: chef/inspec:2.1.83
            name: Syntax check and lint InSpec tests
            script:
              - cd infrastructure/inspec-profiles
              - inspec check aws-baseline
              - inspec check debian-baseline
              - inspec check jenkins-master
  custom:
    detect-infrastructure-state-drift:
      - step:
          image: hashicorp/terraform:0.11.7
          name: Detect Terraform state drift
          script:
            - cd infrastructure
            - terraform init
            - ./terraform/scripts/detect-terraform-state-drift.sh
    run-inspec-infrastructure-tests:
      - step:
          image: chef/inspec:2.1.83
          name: Run tests against current infrastructure
          script:
            - inspec infrastructure/inspec-profiles/jenkins-master -t ssh://ubuntu@<TODO-jenkins-master-dns> -i <TODO-ssh-private-key>
            - inspec infrastructure/inspec-profiles/aws-baseline -t aws://
