name: jenkins-master
title: Jenkins master tests
maintainer: Elliot Pryde
copyright: Elliot Pryde
copyright_email: elliotpryde@gmail.com
license: GPL-3.0
summary: Verify that all Jenkins dependencies are behaving
version: 0.1
supports:
  - os-family: linux
inspec_version: "2.1.83"
depends:
  - name: debian-baseline
    path: ../debian-baseline

