version: '3.2'
services:
  jenkins-master:
    container_name: jenkins-master
    build:
      context: ./build
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
     - "5000:5000"
#    volumes:
#     - type: volume
#       source: /c/jenkins_home
#       target: /var/jenkins_home
    user: jenkins
    env_file: ./jenkins-master.env
