version: '3.2'
services:
  jenkins-master:
    container_name: jenkins-master
    build:
      context: ./build
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 2