version: '2'
services:
  jenkins-master:
    image: chuck202/jenkins-master:0.1
    container_name: jenkins-master
    build:
      context: ./jenkins-master
      dockerfile: Dockerfile
    ports:
      - "50000:50000"
    volumes_from:
      - jenkins-data
    restart: always
    env_file:
      - ./network.env
  jenkins-data:
    image: chuck202/jenkins-data:0.1
    container_name: jenkins-data
    build:
      context: ./jenkins-data
      dockerfile: Dockerfile
  jenkins-nginx:
    image: chuck202/jenkins-nginx:0.1
    container_name: jenkins-nginx
    build:
      context: ./jenkins-nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - jenkins-master