version: '2'
services:
  jenkins-master:
    image: chuck202/jenkins-master:0.1
    container_name: jenkins-master
    build: jenkins-master
    ports:
      - "50000:50000"
    volumes_from:
      - jenkins-data
    restart: always
    env_file:
      - ./network.env
  jenkins-data:
    image: chuck202/jenkins-data:0.1
    container_name: jenkins-data
    build: jenkins-data
  jenkins-nginx:
    image: chuck202/jenkins-nginx:0.1
    container_name: jenkins-nginx
    build: jenkins-nginx
    ports:
      - "80:80"
    links:
      - jenkins-master