version: '2'
services:
  jenkins-master:
    image: chuck202/jenkins-master:0.1
    container_name: jenkins-master
    build:
      context: ./jenkins-master
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes_from:
      - jenkins-data
    restart: always
    env_file:
      - ./network.env
  jenkins-data:
    image: chuck202/jenkins-data:0.1
    container_name: jenkins-data
    build:
      context: ./jenkins-data
      dockerfile: Dockerfile