version: '2'
services:
  master:
    image: chuck202/master:0.1
    container_name: jenkins-master
    build: jenkins-master
    ports:
      - "50000:50000"
    volumes_from:
      - data
    restart: always
    env_file:
      - ./network.env
  data:
    image: chuck202/data:0.1
    container_name: jenkins-data
    build: jenkins-data
  nginx:
    image: chuck202/nginx:0.1
    container_name: jenkins-nginx
    build: jenkins-nginx
    ports:
      - "80:80"
    links:
      - master
  slave:
    image: chuck202/slave:0.1
    container_name: jenkins-slave
    build: jenkins-slave