---
- name: Configure a host which can spin up ephemeral jenkins docker slaves
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_method: sudo

  roles:
    - role: angstwad.docker_ubuntu
      daemon_json:
        hosts:
          - "tcp://0.0.0.0:2376"
