version: '3.2'
services:
  jenkins-master:
    image: jenkins-master:0.1
    container_name: jenkins-master
    build:
      context: ./build
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    env_file:
      - ./network.env
